### PR TITLE
remove transaction 'to' param validation in eth client

### LINKED ISSUE #417: Not possible to deploy contracts via code using sdk 0.3.0
Stack trace:

```
Error: Invalid recipient address
    at EthClient.validateTransaction (Client.js:854)
    at EthClient._callee16$ (Client.js:822)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:264)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/static/js/0.chunk.js:13456:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at EthClient.<anonymous> (asyncToGenerator.js:21)
    at EthClient.prepareAndSignTx (Client.js:842)
    at EthClient._callee17$ (Client.js:870)
    at tryCatch (runtime.js:45)
```

It used to work with 0.2.0, it seems now the code in Client.js is requiring the presence of "to" address in a transaction, but actually this is not always true. When you are deploying a new contract on-chain, the creation transaction does not have a "to" address because it will be determined as a result of the operation:

```
  _proto.validateTransaction = function validateTransaction(txParams) {
    if (!txParams.from || !(0, _web3Utils.isAddress)(txParams.from)) {
      throw new Error('Invalid sender address');
    }

    if (!txParams.to || !(0, _web3Utils.isAddress)(txParams.to)) {
      throw new Error('Invalid recipient address');
    }
  };
```

### PR DESCRIPTION
**Pull request by avclarke**
Closes #417

### CODE REVIEW

**Comment by howleysv** [comment]
Maybe we should still validate `to` if it's provided?

**Comment by wmitsuda** [comment]
Hi all, @howleysv @avclarke , I was the one who opened the original issue. I couldn't wait for the next release, so I just tried the fix directly from the master and apparently just removing the validation does not fix the original issue of sending a transaction without a "to" parameter, which is the case of deploying a new contract.

It is giving the following stack trace now:

```
e: Invalid params
    at Function.e.fromObject (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:64542)
    at Object.next (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:65429)
    at e.__tryOrUnsub (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:10812)
    at e.next (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:9935)
    at e._next (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:8948)
    at e.next (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:8619)
    at e.__tryOrUnsub (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:4871)
    at e.next (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:4016)
    at e._next (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:3068)
    at e.next (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:2739)
    at e.next (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:15512)
    at EventEmitter.i.ipcRenderer.on (/Applications/MainframeOS.app/Contents/Resources/static/preload.bundle.js:16:54300)
    at EventEmitter.emit (events.js:182:13)
```

I can provide some sample code if you need to reproduce.

**Comment by avclarke** [comment]
Hi @wmitsuda, sorry about that, I think we also have some validation in the Client schema here that I missed: https://github.com/MainframeHQ/mainframe-os/blob/b0d952f805ff65455b46194d5655c151eb548fc3/packages/client/src/schema.js#L308

I don't have time to test this right now but feel free to make the change and build from source if you'd like to give this a try and I'll make sure to fully test and get a fix in tomorrow.

**Comment by avclarke** [comment]
Change to schema is merged now @wmitsuda https://github.com/MainframeHQ/mainframe-os/pull/420. Tested deploying a contract and seems to be all good.

**Comment by wmitsuda** [comment]
@avclarke thanks for the quick response! I've updated my local copy and I'm still getting the same errors, but I may be doing something wrong since I'm not still familiar with the project structure.

Is just rebuilding the daemon enough? I mean, using the launcher from the binary distribution connecting to the rebuilt daemon. Or is it necessary to rebuilt the launcher too?

**Comment by wmitsuda** [comment]
Never mind, I think I made it work, I had to run the launcher from the local copy too and apparently it worked now.

**Pull request merged**
